name: 'slither-static-analysis'
description: 'Run slither static analyser for Solidity Smart Contracts'
inputs:
  run-npm-install:
    description: "By default the action will run npm install on the source folder. Set this variable as false to disable it"
    required: false
    default: true
  slither-version:
    description: "Specify slither version to use. It will download it from official github project."
    required: false
    default: "0.8.1"
  high-threshold:
    description: "Action will fail if the number of High findings is equal or bigger then this value (0 to disable)"
    required: false
    default: 1
  medium-threshold:
    description: "Action will fail if the number of Medium findings is equal or bigger then this value (0 to disable)"
    required: false
    default: 1
  low-threshold:
    description: "Action will fail if the number of Low findings is equal or bigger then this value (0 to disable)"
    required: false
    default: 1
  informative-threshold:
    description: "Action will fail if then number of Informative findings is equal or bigger then this value (0 to disable)"
    required: false
    default: 10
  optimization-threshold:
    description: "Action will fail if then number of Optimization findings is equal or bigger then this value (0 to disable)"
    required: false
    default: 1
  projectPath:
    description: "THe path for the smart contracts' project."
    required: false
    default: "."
  slither-params:
    description: "Extra slither parameters to use when running the tool"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'shield'  
  color: 'red'
